trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - "/source/front-end/back-office/modules/account/*"
pr:
  - master

pool:
  vmImage: "ubuntu-latest"

name: "mra-account"

steps:
  - script: |
      echo "Hello from mra-account folder."
