name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - "source/*"

pr:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Hello from root folder."
