trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - "front-end/back-office/bootstrap-container/*"
      - "front-end/back-office/modules/mra-utility/*"
      - "front-end/back-office/modules/mra-account/*"
      - "front-end/back-office/modules/mra-authentication/*"
      - "back-end/Account/*"
      - "back-end/Core/*"
pr:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - script: echo "Hello from '/' root folder"