name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - "/source/front-end/back-office/modules/mra-admin/*"

pr:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install
    jobs:
      - job: InstallJob
        displayName: InstallJob
        steps:
          - script: yarn install
            name: YarnInstall
            displayName: Yarn install
            workingDirectory: "$(Workspace)"

  - stage: CodeReview
    jobs:
      - job: CodeReviewJob
        displayName: CodeReviewJob
        steps:
          - script: yarn format && yarn check-format
            name: YarnFormat
            displayName: Yarn format
            workingDirectory: "$(Workspace)"
          - script: yarn lint
            name: YarnLint
            displayName: Yarn lint
            workingDirectory: "$(Workspace)"

  - stage: Build
    jobs:
      - job: BuildJob
        displayName: BuildJob
        steps:
          - script: yarn build
            name: YarnBuild
            displayName: Yarn build
            workingDirectory: "$(Workspace)"
            
  - stage: Deploy
    jobs:
      - job: DeployFirebase
        displayName:
        steps:
          - script: 'firebase deploy --token "$(FIREBASE_TOKEN)" -m "$(Build.BuildNumber)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)\\build'
            displayName: 'firebase publish -m "$(Build.BuildNumber)"'
