name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - "/source/front-end/back-office/mra-admin/*"

pr:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: FIREBASE_TOKEN
    value: 0e7EL5p0cB3mwCgYIARAAGA4SNwF-L9IrRJTJPOXWPVQXxHCQT7HkQbyqDBjJHNmSR4kr1hea6j_B4axlcXw9kcdFT_fS_p5WiTQ
  - name: sourceDictionary
    value: $(Pipeline.Workspace)/s/source/front-end/back-office/mra-admin/

stages:
  - stage: Install
    jobs:
      - job: InstallNodeJob
        displayName: InstallNodeJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"
          - script: npm install -g yarn
      - job: InstallJob
        displayName: InstallJob
        steps:
          - script: yarn install
            name: YarnInstall
            displayName: Yarn install
            workingDirectory: "$(sourceDictionary)"
      - job: CodeReviewJob
        displayName: CodeReviewJob
        steps:
          - script: yarn check-format
            name: YarnCheckFormat
            displayName: Yarn check format
            workingDirectory: "$(sourceDictionary)"

  - stage: Build
    jobs:
      - job: BuildJob
        displayName: BuildJob
        steps:
          - script: yarn build
            name: YarnBuild
            displayName: Yarn build
            workingDirectory: "$(sourceDictionary)"

  - stage: Deploy
    condition: and(succeeded(), eq(variables.isMaster, 'true'))
    jobs:
      - job: DeployFirebase
        displayName:
        steps:
          - script: 'firebase deploy --token "$(FIREBASE_TOKEN)" -m "$(Build.BuildNumber)"'
            workingDirectory: "$(sourceDictionary)/build"
            displayName: 'firebase publish -m "$(Build.BuildNumber)"'
