name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - "/source/back-end/Account/*"
pr:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Hello from backend Account folder."
