version: "3.4"

services:
  account-service:
    container_name: account-service
    build:
      context: ../
      dockerfile: ${BE_BASE_FOLDER}/Account/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - ConnectionStrings__SqlConnection=Server=${BE_ACCOUNT_SQL_DATABASE_HOST},${BE_ACCOUNT_SQL_DATABASE_PORT};Database=${BE_ACCOUNT_SQL_DATABASE};User Id=${BE_ACCOUNT_SQL_DATABASE_USER_ID};Password=${BE_ACCOUNT_SQL_DATABASE_PASSWORD};
    ports:
      - "${BE_ACCOUNT_PORT}:80"
    restart: always
    networks:
      - back-end
networks:
  back-end:
