version: "3.4"

services:
  # bootstrap-container:
  #   build:
  #     context: ../${FE_BO_BASE_FOLDER}/bootstrap-container/
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - HOST=${FE_BO_BOOTSTRAP_HOST}
  #     - ENV=docker
  #   ports:
  #     - "${FE_BO_BOOTSTRAP_PORT}:80"
  #   restart: always
  #   networks:
  #     - back-office
  # authentication-module:
  #   build:
  #     context: ../${FE_BO_BASE_FOLDER}/modules/mra-authentication/
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "${FE_BO_AUTHENTICATION_PORT}:80"
  #   restart: always
  #   networks:
  #     - back-office
  account-module:
    build:
      context: ../${FE_BO_BASE_FOLDER}/modules/mra-account/
      dockerfile: Dockerfile.dev
    command: yarn start
    restart: always
    networks:
      - back-office
  # utility-module:
  #   build:
  #     context: ../${FE_BO_BASE_FOLDER}/modules/mra-utility/
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "${FE_BO_UTILITY_PORT}:80"
  #   environment:
  #     - AWS_COGNITO_REGION=${FE_BO_UTILITY_AWS_COGNITO_REGION}
  #     - AWS_COGNITO_POOL_ID=${FE_BO_UTILITY_AWS_COGNITO_POOL_ID}
  #     - AWS_COGNITO_CLIENT_ID=${FE_BO_UTILITY_AWS_COGNITO_CLIENT_ID}
  #   restart: always
  #   networks:
  #     - back-office
networks:
  back-office:
