version: "3.5"
services:
    # sql-server:
    #     container_name: sqlserver
    #     image: "mcr.microsoft.com/mssql/server"
    #     environment:
    #         SA_PASSWORD: "P@ssw0rd"
    #         ACCEPT_EULA: "Y"
    #     ports: 
    #         - "1433:1433"
    #     restart: on-failure
    #     networks: 
    #         - software
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3-management-alpine"
        restart: on-failure
        environment:
            - RABBITMQ_DEFAULT_USER=admin 
            - RABBITMQ_DEFAULT_PASS=P@ssw0rd
            - RABBITMQ_ERLANG_COOKIE=s3cr3tc00ki3
        networks:
            - software
        ports: 
            - 5672:5672
            - 15672:15672
    # smtp4dev:
    #     container_name: smtp
    #     image: rnwood/smtp4dev:v3
    #     ports:
    #         - "3000:80"
    #         - "2525:25"
    #     networks: 
    #         - software
    #     restart: on-failure
    zipkin:
        image: openzipkin/zipkin:latest
        container_name: zipkin
        ports: 
            - "9411:9411"
        networks: 
            - software
        restart: on-failure
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mra_account
        ports:
            - "5432:5432"
        restart: on-failure
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - "6789:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
        restart: on-failure
        networks: 
            - software
networks: 
    software: