version: "3.5"

services:
  backoffice:
    build:
      context: ../${FE_BO_FOLDER}/mra-admin/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - HOST=${FE_BO_HOST}
    ports: 
      - ${FE_BO_PORT}:80
    restart: always
    networks:
      - front-end
networks:
  front-end:
