version: "3.4"

services:
  bootstrap-container:
    build:
      context: ../
      dockerfile: ${FE_BO_BASE_FOLDER}/bootstrap-container/Dockerfile.dev
    environment:
      - HOST=${FE_BO_BOOTSTRAP_HOST}
    ports:
      - "${FE_BO_BOOTSTRAP_PORT}:80"
    restart: always
    networks:
      - back-office
  authentication-module:
    build:
      context: ../
      dockerfile: ${FE_BO_BASE_FOLDER}/modules/mra-authentication/Dockerfile.dev
    ports:
      - "${FE_BO_AUTHENTICATION_PORT}:80"
    restart: always
    networks:
      - back-office
  # account-module:
  #   container_name: account-module
  #   build:
  #     context: ../
  #     dockerfile: ${FE_BO_BASE_FOLDER}/modules/mra-account/Dockerfile.dev
  #   ports:
  #     - "${FE_BO_ACCOUNT_PORT}:80"
  #   restart: always
  #   networks:
  #     - back-office
  utility-module:
    build:
      context: ../
      dockerfile: ${FE_BO_BASE_FOLDER}/modules/mra-utility/Dockerfile.dev
    ports:
      - "${FE_BO_UTILITY_PORT}:80"
    environment:
      - AWS_COGNITO_REGION=${FE_BO_UTILITY_AWS_COGNITO_REGION}
      - AWS_COGNITO_POOL_ID=${FE_BO_UTILITY_AWS_COGNITO_POOL_ID}
      - AWS_COGNITO_CLIENT_ID=${FE_BO_UTILITY_AWS_COGNITO_CLIENT_ID}
    restart: always
    networks:
      - back-office
networks:
  back-office:
