version: "3.5"

services:
  account-service:
    container_name: account-service
    build:
      context: ../
      dockerfile: ${BE_BASE_FOLDER}/Account/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - ConnectionStrings__SqlConnection=${BE_ACCOUNT_CONNECTION_STRING}
      - MessageBroker__Host=${BE_ACCOUNT_MESSAGE_BROKER_HOST}
    ports:
      - "${BE_ACCOUNT_PORT}:80"
    restart: always
    networks:
      - back-end
networks:
  back-end:
