name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - "/source/front-end/back-office/modules/mra-utility/*"
pr:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Hello from mra-utility folder."
